version: "3.3"
services:
  cool:
    build:
      context: ""
    image: cool:latest
    volumes:
      - type: bind
        source: ./p1
        target: /usr/class/cs143/p1
      - type: bind
        source: ./p2
        target: /usr/class/cs143/p2
      - type: bind
        source: ./p3
        target: /usr/class/cs143/p3
      - type: bind
        source: ./p4
        target: /usr/class/cs143/p4


