FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install wget flex bison build-essential csh openjdk-8-jdk libxaw7-dev

WORKDIR /usr/class

RUN wget -O student-dist.tar.gz https://courses.edx.org/asset-v1:StanfordOnline+SOE.YCSCS1+1T2020+type@asset+block@student-dist.tar.gz

RUN tar -xf student-dist.tar.gz 

# tagged as `cool:latest`