version: "3.8"
services:
  cool:
    build:
      context: ""
    image: cool:latest
    volumes:
      - type: bind
        source: ./p1
        target: /usr/class/p1
      - type: bind
        source: ./p2
        target: /usr/class/p2
      - type: bind
        source: ./p3
        target: /usr/class/p3

